development:
  host: localhost
  port: 27017
  database: cbook-dev
  logfile: development.log
    
production:
  host: localhost
  port: 27017
  database: app3237740
  logfile: production.log
    
environment: development